---
title: "Comparing the Effectiveness of VR-Based and CBT Interventions for Autism Spectrum
  Disorder"
author: "Brendan Flaherty (D00285274) & Jeremiah Spillane (D00295490)"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    df_print: paged
  html_notebook:
    toc: true
---

# Data Analytics for Immersive Environments (COMPC9047)

## Investigating the Impact of Therapeutic Interventions on Austistic Traits using the Autism Spectrum Quotient (AQ)

**Participants:** Brendan Flaherty (D00285274) & Jeremiah Spillane (D00295490) **Module:** Data Analytics for Immersive Environments (COMPC9047) **Date:** `r Sys.Date()`

------------------------------------------------------------------------

# Abstract 
## Aim and rationale 
## Participants and setting 
## Experiment design 
## Results gathering
## Findings/implications

# Introduction

## Topic and Context

Briefly describe the Autism Spectrum Disorder (ASD) as a neurodevelopmental spectrum condition and introduce the concept of neurodiversity.

## Rationale

Why are we doing this study? This study investigates which method yileds greater improvements in AQ

## Hypotesis

#### **H1:** After controlling for baseline AQ, there will be no group differences in post-treatment (null-hypothesis)

#### **H2:** Both CBT abd VR therapy groups will show significant reductions in AQ scores from pre-treatment to post-treatment, while the control group will not

#### **H3:** ???

# Method

#### **Participants:** 300 adults (M = 150, F = 150), aged 12-40. Random assignment to CBT (n = 100), VR (n = 100), Control (n = 100).

#### **Design:** Mixed 3 (Group: CBT, VR, Control - between subjects) x 2 (Time: Pre, Post - within-subjects) design.

#### **Materials:** Autism Spectrum Quotient (AQ) 50-item questionnaire, scored 0-50.1.

#### **Procedure:** Each participant completed AQ before and after 12 weeks of therapy.

-   CBT: Weekly sessions on social/emotional regulation.

-   VR: Immersive simulations for social interaction.

-   Control: No intervention.

Data recorded in columns P1_Pre_Score and P2_Post_Score.

# Results

### \*\*Data Cleaning\*

```{r Data Cleaning, message=TRUE, warning=TRUE, paged.print=FALSE}
# Adding librarys to notebook to run the code correctly
library(tidyverse)
library(ggpubr)
library(rstatix)
library(knitr)
# Read the data frames of the .csv file
df <- read_csv("CA1_Autism_VR_Study_Data_Final.csv")
# Check the column names
colnames(df)
# Change column names to lowercase
df <- df %>% rename_with(tolower) %>% mutate(group = str_trim(tolower(group)))
# Inspect Structure
glimpse(df)
summary(select(df, p1_pre_score, p2_post_score))
# Check for missing values
sapply(df, function(x) sum(is.na(x)))
# Check for values outside the scope of the questionnaire - 0 - 50.1
filter(df, p1_pre_score < 0 | p1_pre_score > 50.1 | p2_post_score < 0 | p2_post_score > 50.1)
# Drop incomplete rows
df <- df %>% drop_na(p1_pre_score, p2_post_score)
# Identify change_score (pre-post AQ)
df <- df %>% mutate(change_score = p1_pre_score - p2_post_score)
# Confirm groups
unique(df$group)
# Check for summary of all columns
summary(select(df, p1_pre_score, p2_post_score, change_score))
```

### **Descriptive Statistics**

#### **Plots**

```{r box plot, message=TRUE, warning=TRUE}
# BoxPlot created to show pre-treatment AQ scores
pre_box <- ggplot(df, aes(x = group, y = p1_pre_score, fill = group)) + geom_boxplot() + scale_fill_manual(values = c("skyblue", "lightgreen", "orange")) + labs(title = "Pre-Treatment AQ Scores",  x = "Group", y = "AQ Score (0–50)") + theme_minimal(base_size = 13) + theme(plot.title = element_text(hjust = 0.5, face = "bold"))

# BoxPlot created to show post-treatment AQ scores
post_box <- ggplot(df, aes(x = group, y = p2_post_score, fill = group)) + geom_boxplot() + scale_fill_manual(values = c("skyblue", "lightgreen", "orange")) + labs(title = "Post-Treatment AQ Scores",  x = "Group", y = "AQ Score (0–50)") + theme_minimal(base_size = 13) + theme(plot.title = element_text(hjust = 0.5, face = "bold"))

# Use ggpbr library to arrange histograms side-by-side to show difference pre and post treatment
library(ggpubr)
ggarrange(pre_box, post_box, ncol = 2, common.legend = TRUE, legend = "bottom")

# Pre-treatment AQ scores shows similar median. Post-Treatment AQ scores show VR Therapy group noticeably lower indicating greater improvement. Boxes show IQR and whiskers show outliers

```

```{r bar chart, message=TRUE, warning=TRUE}
# Summarise and group mean score data by group for creating bar chart
avg_dep_scores <- df %>% summarise(mean_pre = mean(p1_pre_score), mean_post = mean(p2_post_score), .by = group) %>% pivot_longer(cols = c(mean_pre, mean_post), names_to = "time", values_to = "mean_score") %>% mutate(time = recode(time, "mean_pre" = "Pre-Treatment", "mean_post" = "Post-Treatment"))

# Bar chart created to show mean AQ scores before and after treatment for each group
ggplot(avg_dep_scores, aes(x = group, y = mean_score, fill = time)) + geom_bar(stat = "identity", position = position_dodge()) + scale_fill_manual(values = c("orange", "skyblue")) + labs(title = "Average AQ (Depression) Scores by Group", x = "Therapy Group", y = "Mean AQ Score (0-50)" ) + theme_minimal(base_size = 13)

# Both CBT and VR Therapy groups show reduced mean AQ scores after treatment
```

```{r line-graph, message=TRUE, warning=TRUE}
# Summarise and group mean score data by time for creating line graph
avg_dep_time <- df %>% summarise(mean_pre = mean(p1_pre_score), mean_post = mean(p2_post_score), .by = group) %>% pivot_longer(cols = c(mean_pre, mean_post), names_to = "time", values_to = "mean_score") %>% mutate(time = recode(time, "mean_pre" = "Pre-Treatment", "mean_post" = "Post-Treatment"))

# Line graph showing mean AQ scores for each group pre and post treatment
ggplot(avg_dep_time, aes(x = time, y = mean_score, group = group, color = group)) + geom_line(linewidth = 1.2) + geom_point(size = 13) + scale_colour_manual(values = c("orange", "skyblue", "lightgreen")) + labs(title = "Change in Mean AQ Scores Over Time by Group", x = "Time Point", y = "Mean AQ Score (0-50)" ) + theme_minimal(base_size = 13)

# Both CBT and VR Therapy groups downward trends from pre-treatment to post-treatment - VR Therapy shows greater reduction 
```

```{r histograms, message=TRUE, warning=TRUE}
# Calculate pre-treatment AQ score distributions across the 3 groups
pre_hist <- ggplot(df, aes(x = p1_pre_score, fill = group)) + geom_histogram(binwidth = 2, alpha = 0.6, position = "identity", color = "black") + geom_vline(data = df %>% group_by(group) %>% summarise(mean_pre = mean(p1_pre_score)), aes(xintercept = mean_pre, colour = group), linetype = "dashed", linewidth = 1) +scale_fill_manual(values = c("orange", "skyblue", "lightgreen")) + scale_colour_manual(values = c("orange", "skyblue", "lightgreen")) + labs(title = "Pre-Treatment AQ Score Distribution", x = "AQ Score (0 -50)", y = "Frequency") + theme_minimal(base_size = 13) + theme(plot.title = element_text(hjust = 0.5, face = "bold"))

# Calculate post-treatment AQ score distributions across the 3 groups
post_hist <- ggplot(df, aes(x = p2_post_score, fill = group)) + geom_histogram(binwidth = 2, alpha = 0.7, colour = "black") + geom_vline(data = df %>% group_by(group) %>% summarise(mean_post = mean(p2_post_score)), aes(xintercept = mean_post, color = group), linetype = "dashed", linewidth = 1) + scale_fill_manual(values = c("orange", "skyblue", "lightgreen")) + scale_colour_manual(values = c("orange", "skyblue", "lightgreen")) + labs(title = "Post-Treatment AQ Score Distribution", x = "AQ Score (0-50)", y = "Frequency") + theme_minimal(base_size = 13) + theme(plot.title = element_text(hjust = 0.5, face = "bold"))

# Use ggpbr library to arrange histograms side-by-side to show difference pre and post treatment
library(ggpubr)
ggarrange(pre_hist, post_hist, ncol = 2, common.legend = TRUE, legend = "bottom")

# All groups show similar AQ score pre-treatment. Post-treatment, both CBT and VR Therapy groups show lower AQ score indicating improvement
```

```{r scatterplot, message=TRUE, warning=TRUE}

# Scatterplot showing relationship between pre-treatment AQ scores and change in AQ scores post-treatment
ggplot(df, aes(x = p1_pre_score, y = change_score, colour = group)) + geom_point(size = 3, alpha = 0.7) + geom_smooth(method = "lm", se = FALSE, linetype = "dashed") + scale_colour_manual(values = c("orange", "skyblue", "lightgreen")) + labs(title = "Pre-Treatment AQ vs Change in Score", x = "Pre-Treatment AQ Score", y = "Change in AQ (Pre - Post, Positive = Improvement)" ) + theme_minimal()

# A positive change indicates improvement - Participants with higher pre-treatment AQ scores tended to have a larger improvement

```

### **Inferential Statistics**

```{r paired t-test, message=TRUE, warning=TRUE}
# Assign and filter by group
cbt <- df %>% filter(group == "cbt")
vr <- df %>% filter(group == "vr")
control <- df %>% filter (group == "control")

# t-test by group 
t_cbt <- t.test(cbt$p1_pre_score, cbt$p2_post_score, paired = TRUE)
t_vr <- t.test(vr$p1_pre_score, vr$p2_post_score, paired = TRUE)
t_control <- t.test(control$p1_pre_score, control$p2_post_score, paired = TRUE)

# Output results of t-test in list
list(CBT = t_cbt, VR = t_vr, CONTROL = t_control)

# Interpretation: 
# CBT - significant improvement: t=22.9, p<.001. Mean diff = 10.99. CI between 9.2-11
# VR - Very big improvement: t=37.6, p<.001. Mean diff = 18.62. CI between 17.6-19.6
# CONTROL - no significant change: t=1.59, p=0.115. Mean diff = 0.6. CI include 0 - no change

# Results suggest that both CBT and VR reduced AQ scores with VR Therapy having a significant impact
```


#### **Probability**

#### **Hypothesis Testing**

#### **Regresssion Analysis**

#### **Confidence Interval**

```{r}

```

### **Statistical tests**

### **Hypothesis 1 -**

### **Hypothesis 2 -**

### **Hypothesis 3 -**

### **Magnitude and direction of results**

# Discussion

### Outline findings and relation to the hypothesis

**Paired t-test results**
Undertaken to analyse changes in the group of AQ scores pre and post-treatment
CBT - significant improvement: t=22.9, p<.001. Mean diff = 10.99. CI between 9.2-11
VR - Very big improvement: t=37.6, p<.001. Mean diff = 18.62. CI between 17.6-19.6
CONTROL - no significant change: t=1.59, p=0.115. Mean diff = 0.6. CI include 0 - no change
Results suggest that both CBT and VR reduced AQ scores with VR Therapy having a significant impact



#### Limitations

------------------------------------------------------------------------

# References
